<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Chaya" failures="1" tests="6" name="Test3" time="5.623" errors="0" timestamp="2024-10-16T11:33:31 EDT">
  <testcase classname="StepDefination.RegistratnStepDefination" name="callingobjects" time="2.825"/>
  <testcase classname="StepDefination.RegistratnStepDefination" name="enter_username_password_click_btn" time="0.941"/>
  <testcase classname="StepDefination.RegistratnStepDefination" name="click_registration_link_and_user_is_in_registration_page" time="0.276"/>
  <testcase classname="StepDefination.RegistratnStepDefination" name="user_enter_credentials" time="0.694"/>
  <testcase classname="StepDefination.RegistratnStepDefination" name="clickRegisterbtn" time="0.509">
    <failure type="java.lang.AssertionError" message="expected [Credentials already exists] but found [password_mismatch:The two password fields didn’t match.]">
      <![CDATA[java.lang.AssertionError: expected [Credentials already exists] but found [password_mismatch:The two password fields didn’t match.]
at StepDefination.RegistratnStepDefination.clickRegisterbtn(RegistratnStepDefination.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- clickRegisterbtn -->
  <testcase classname="StepDefination.RegistratnStepDefination" name="quitmethod" time="0.326"/>
</testsuite> <!-- Test3 -->
